#!/bin/bash
set -euo pipefail

path="$1"

apt-get update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository ppa:deadsnakes/ppa

apt-get update
apt install -y "$path"

docker-push-latest-if-changed --help
