#!/bin/bash
set -euo pipefail

path="$1"

apt-get update
apt-get -y install --no-install-recommends gdebi-core software-properties-common

apt-get update
gdebi -n "$path"

docker-push-latest-if-changed --help
